[tools]
biome = "latest"
bun = "1.4.2"

[tasks.dev]
run = "bun dev"

[tasks.build]
run = "bun run build"

[tasks.start]
run = "bun start"

[tasks.lint]
run = "biome check"

[tasks.test]
run = "bun test"

[tasks.check]
run = "bun run check"

[tasks.format]
run = "biome format --write"
