import type { Metadata } from "next";
import "@/styles/globals.css";
import { Provider } from "jotai";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity/visual-editing";
import DisableDraftMode from "@/components/utility/DIsableDraftMode";
import { geistMono, geistSans } from "@/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body
          className={cn(geistSans.variable, geistMono.variable, "antialiased")}
        >
          {children}
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
        </body>
      </html>
    </Provider>
  );
}
